openapi: 3.1.0
info:
  title: Brand Identity API
  version: 1.0.0
servers:
  - url: https://7cc4ffb1ef56.ngrok-free.app/
paths:
  /search:
    post:
      operationId: ragSearch
      summary: RAG search across brand corpus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query: { type: string }
                k: { type: integer, default: 5, minimum: 1, maximum: 20 }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  matches:
                    type: array
                    items:
                      type: object
                      properties:
                        text: { type: string }
                        source: { type: string }
                        score: { type: number }
  /answer:
    post:
      operationId: brandAnswer
      summary: Compose an on-brand answer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question: { type: string }
                k: { type: integer, default: 5, minimum: 1, maximum: 20 }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  text: { type: string }
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: string }
                        url: { type: string }
                        note: { type: string }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
