name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      GROK_API_KEY:           ${{ secrets.GROK_API_KEY }}
      NEO4J_DATABASE:         ${{ secrets.NEO4J_DATABASE }}
      NEO4J_PASSWORD:         ${{ secrets.NEO4J_PASSWORD }}
      NEO4J_URI:              ${{ secrets.NEO4J_URI }}
      NEO4J_USER:             ${{ secrets.NEO4J_USER }}
      OPENROUTER_API_KEY:     ${{ secrets.OPENROUTER_API_KEY }}
      OPENROUTER_BASE_URL:    ${{ secrets.OPENROUTER_BASE_URL }}
      OPENROUTER_MODEL:       ${{ secrets.OPENROUTER_MODEL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Fail fast if any required secret is missing
      - name: Check required secrets
        run: |
          missing=0
          for v in GROK_API_KEY NEO4J_DATABASE NEO4J_PASSWORD NEO4J_URI NEO4J_USER OPENROUTER_API_KEY OPENROUTER_MODEL; do
            if [ -z "${!v}" ]; then echo "::error title=Missing secret::$v is not set"; missing=1; fi
          done
          # Add RAG_ENDPOINT to the list if you really use it:
          # for v in ... RAG_ENDPOINT; do ...
          if [ "$missing" -ne 0 ]; then exit 1; fi

      - run: npm ci
      - run: npm test

      # Safe presence checks (never print values)
      - name: Debug presence
        run: |
          for v in NEO4J_URI OPENROUTER_BASE_URL RAG_ENDPOINT; do
            printf "%s is set: %s\n" "$v" "$( [ -n "${!v}" ] && echo yes || echo no )"
          done
